name: Generate RSS Feed

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate_rss:
    permissions:
      contents: write  # for peaceiris/actions-gh-pages to push pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate RSS feeds
        run: |
          python generate_rss.py visprsd
          python generate_rss.py ncrprsd

      - name: Deploy RSS feed
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: rss-feed
          force_orphan: true
